# Generated by Django 5.2.7 on 2025-11-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_fotografia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='publicacao',
            field=models.BooleanField(default=False),
        ),
    ]
