# Generated by Django 5.2.7 on 2025-11-06 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_postagem',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
